# This is a basic workflow to help you get started with Actions
name: Compile module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  compile:
    name: Compile on ${{ matrix.os }} for nginx ${{ matrix.nginx_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nginx_version: ['1.18.0', '1.19.0']
        # The type of runner that the job will run on
        os: [ubuntu-latest, ubuntu-16.04]
   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    # Runs a set of commands using the runners shell
    - name: Configure compilation setting
      run: |
        cd $GITHUB_WORKSPACE
        wget https://nginx.org/download/nginx-${{ matrix.nginx_version }}.tar.gz
        tar -xzvf nginx-${{ matrix.os }}.tar.gz

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: sudo apt-get install gcc make

    - name: Compile dynamic module
      run: |
        cd $GITHUB_WORKSPACE/nginx-${{ matrix.os }}
        ./configure --with-compat --add-dynamic-module=$GITHUB_WORKSPACE/nginx-vod-module
        make modules

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: nginx-vod-module for nginx ${{ matrix.nginx_version }} on ${{ matrix.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: $GITHUB_WORKSPACE//objs
