# This is a basic workflow to help you get started with Actions

name: Compile module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  compile:
    name: Compile on ${{ matrix.os }} for nginx ${{ matrix.nginx_version }}
    strategy:
      matrix:
        nginx_version: ['1.18.0', '1.19.0']
        # The type of runner that the job will run on
        os: [ubuntu-latest, ubuntu-16.04]
   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - submodules: true

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: sudo apt-get install gcc

    # Runs a set of commands using the runners shell
    - name: Configure compilation setting
      run: |
        cd $GITHUB_WORKSPACE/nginx-${{ nginx_version }}
        ./configure --with-compat --add-dynamic-module=$GITHUB_WORKSPACE/nginx-vod-module
