# This is a basic workflow to help you get started with Actions
name: Compile module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "compile"
  compile:
    name: Compile on ${{ matrix.os }} for nginx ${{ matrix.nginx_version }}
    runs-on: ${{ matrix.os }}
    env:
      ffmpeg_version: 4.2.3
      pcre_version: 8.44
      zlib_version: 1.2.11
      module_version: 1.26

    strategy:
      matrix:
        nginx_version: ['1.18.0', '1.19.0']
        # The type of runner that the job will run on
        os: [ubuntu-latest, ubuntu-16.04]
   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Grab comilation sources
    - name: Download ffmpeg
      run: |
        cd $GITHUB_WORKSPACE
        wget https://ffmpeg.org/releases/ffmpeg-${{ $env:ffmpeg_version }}.tar.gz
        tar -xzvf ffmpeg-${{ $env:ffmpeg_version }}.tar.gz

    - name: Download nginx
      run: |
        cd $GITHUB_WORKSPACE
        wget https://nginx.org/download/nginx-${{ matrix.nginx_version }}.tar.gz
        tar -xzvf nginx-${{ matrix.nginx_version }}.tar.gz

    - name: Download nginx-vod-module
      run: |
        cd $GITHUB_WORKSPACE
        wget https://github.com/kaltura/nginx-vod-module/archive/${{ $env:module_version }}.tar.gz
        tar -xzvf ${{ $env:module_version }}.tar.gz
      
    - name: Download pcre
      run: |
        cd $GITHUB_WORKSPACE
        wget https://ftp.pcre.org/pub/pcre/pcre-${{ $env:pcre_version }}.tar.gz
        tar -xzvf pcre-${{ $env:pcre_version }}.tar.gz
        
    - name: Download zlib
      run: |
        cd $GITHUB_WORKSPACE
        wget https://www.zlib.net/zlib-${{ $env:zlib_version }}.tar.gz
        tar -xzvf zlib-${{ $env:zlib_version }}.tar.gz
        
    # Grab prebuilts from apt
    - name: Install dependencies with apt
      run: sudo apt-get install gcc make yasm pkg-config libxml2-dev -y

    # Compile ffmpeg (since it is required for libavcodec and libavfilter)
    - name: Compile ffmpeg
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-${{ $env:ffmpeg_version }}
        ./configure \
        --enable-shared \
        --enable-gpl \
        --enable-nonfree \
        --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' \
        --extra-ldflags='-Wl,-z,relro'
        make
        export LD_LIBRARY_PATH=/usr/local/lib
        export LIBRARY_PATH=/usr/local/lib
        export C_INCLUDE_PATH=/usr/local/include

    - name: Compile dynamic module
      run: |
        cd $GITHUB_WORKSPACE/nginx-${{ matrix.nginx_version }}
        ./configure --with-compat --add-dynamic-module=$GITHUB_WORKSPACE/nginx-vod-module-${{ $env:module_version }}/ \
        --with-pcre=$GITHUB_WORKSPACE/pcre-${{ $env:pcre_version}} \
        --with-zlib=$GITHUB_WORKSPACE/zlib-${{ $env:zlib_version }}
        make modules
        ls -l $GITHUB_WORKSPACE/nginx-${{ matrix.nginx_version }}/objs

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: nginx-vod-module-nginx-${{ matrix.nginx_version }}-${{ matrix.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: $GITHUB_WORKSPACE/nginx-${{ matrix.nginx_version }}/objs/
